"""Terminal-profile emitter for tui-comparison captures.

Every run writes a ``profile.yaml`` alongside the raw/txt/png artifacts
so reviewers can see the exact capture conditions — the terminal
environment, the geometry, the DSR shim version, and what DSR queries
were answered during capture.

Format is intentionally minimal YAML so it roundtrips cleanly and
diff-friendly. Uses stdlib only (no yaml dep; we hand-write the subset
we need).
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from pathlib import Path


@dataclass
class TermProfile:
    """Captured environment + shim state for one capture run."""

    # Environment
    term: str = ""
    colorterm: str = ""
    # Geometry
    rows: int = 0
    cols: int = 0
    # Timing
    boot_budget_s: float = 0.0
    # DSR shim
    dsr_shim_version: str = ""
    dsr_responses_served: list[str] = field(default_factory=list)
    # Tool identification
    tool: str = ""
    tool_version: str = ""
    scenario: str = ""

    @classmethod
    def from_env(
        cls,
        *,
        rows: int,
        cols: int,
        boot_budget_s: float,
        tool: str,
        tool_version: str,
        scenario: str,
    ) -> "TermProfile":
        return cls(
            term=os.environ.get("TERM", ""),
            colorterm=os.environ.get("COLORTERM", ""),
            rows=rows,
            cols=cols,
            boot_budget_s=boot_budget_s,
            tool=tool,
            tool_version=tool_version,
            scenario=scenario,
        )

    def update_dsr(self, shim_version: str, served: list[str]) -> None:
        self.dsr_shim_version = shim_version
        self.dsr_responses_served = list(served)

    def to_yaml(self) -> str:
        """Emit minimal YAML. Keeps ordering stable for diff-friendly output."""
        lines = [
            "# Terminal profile for this capture run.",
            "# Generated by autocode/tests/tui-comparison/profile.py",
            f"tool: {_yaml_str(self.tool)}",
            f"tool_version: {_yaml_str(self.tool_version)}",
            f"scenario: {_yaml_str(self.scenario)}",
            f"term: {_yaml_str(self.term)}",
            f"colorterm: {_yaml_str(self.colorterm)}",
            f"rows: {self.rows}",
            f"cols: {self.cols}",
            f"boot_budget_s: {self.boot_budget_s}",
            f"dsr_shim_version: {_yaml_str(self.dsr_shim_version)}",
            "dsr_responses_served:",
        ]
        if self.dsr_responses_served:
            for label in self.dsr_responses_served:
                lines.append(f"  - {_yaml_str(label)}")
        else:
            lines[-1] = "dsr_responses_served: []"
        return "\n".join(lines) + "\n"

    def write(self, path: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_yaml())
        return path

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, sort_keys=True)


def _yaml_str(value: str) -> str:
    """Quote a string for YAML safely."""
    if value == "" or any(ch in value for ch in ":#\n&*'\"`"):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value
