package main

import "math/rand"

// spinnerVerbs — Claude Code uses 187 rotating verbs during generation.
// These rotate every ~3 seconds to show the agent is alive and working.
var spinnerVerbs = []string{
	"Thinking",
	"Reasoning",
	"Analyzing",
	"Pondering",
	"Considering",
	"Exploring",
	"Investigating",
	"Processing",
	"Evaluating",
	"Examining",
	"Contemplating",
	"Deliberating",
	"Researching",
	"Synthesizing",
	"Formulating",
	"Computing",
	"Deducing",
	"Inferring",
	"Reflecting",
	"Assessing",
	"Mapping",
	"Tracing",
	"Parsing",
	"Scanning",
	"Searching",
	"Reading",
	"Understanding",
	"Decoding",
	"Untangling",
	"Connecting",
	"Structuring",
	"Organizing",
	"Planning",
	"Strategizing",
	"Drafting",
	"Composing",
	"Constructing",
	"Building",
	"Assembling",
	"Weaving",
	"Crafting",
	"Refining",
	"Polishing",
	"Optimizing",
	"Iterating",
	"Revising",
	"Debugging",
	"Fixing",
	"Patching",
	"Resolving",
	"Troubleshooting",
	"Diagnosing",
	"Inspecting",
	"Verifying",
	"Validating",
	"Testing",
	"Checking",
	"Reviewing",
	"Auditing",
	"Comparing",
	"Contrasting",
	"Weighing",
	"Balancing",
	"Calibrating",
	"Tuning",
	"Adjusting",
	"Aligning",
	"Harmonizing",
	"Integrating",
	"Consolidating",
	"Merging",
	"Compiling",
	"Generating",
	"Producing",
	"Rendering",
	"Materializing",
	"Manifesting",
	"Conjuring",
	"Imagining",
	"Envisioning",
	"Dreaming",
	"Designing",
	"Architecting",
	"Engineering",
	"Prototyping",
	"Modeling",
	"Simulating",
	"Projecting",
	"Forecasting",
	"Predicting",
	"Hypothesizing",
	"Theorizing",
	"Speculating",
	"Brainstorming",
	"Ideating",
	"Innovating",
	"Discovering",
	"Uncovering",
	"Excavating",
	"Mining",
	"Distilling",
	"Extracting",
	"Isolating",
	"Filtering",
	"Sifting",
	"Sorting",
	"Classifying",
	"Categorizing",
	"Indexing",
	"Cataloging",
	"Annotating",
	"Documenting",
	"Recording",
	"Logging",
	"Tracking",
	"Monitoring",
	"Observing",
	"Watching",
	"Listening",
	"Absorbing",
	"Learning",
	"Adapting",
	"Evolving",
	"Growing",
	"Expanding",
	"Deepening",
	"Sharpening",
	"Focusing",
	"Concentrating",
	"Zeroing in",
	"Homing in",
	"Narrowing down",
	"Drilling down",
	"Diving deep",
	"Going deeper",
	"Pushing forward",
	"Pressing on",
	"Forging ahead",
	"Breaking through",
	"Pivoting",
	"Rethinking",
	"Reconsidering",
	"Reframing",
	"Reimagining",
	"Reinventing",
	"Transforming",
	"Translating",
	"Interpreting",
	"Deciphering",
	"Cracking",
	"Solving",
	"Unwinding",
	"Unraveling",
	"Detangling",
	"Simplifying",
	"Streamlining",
	"Distilling",
	"Condensing",
	"Summarizing",
	"Abstracting",
	"Generalizing",
	"Specializing",
	"Customizing",
	"Tailoring",
	"Personalizing",
	"Contextualizing",
	"Grounding",
	"Anchoring",
	"Establishing",
	"Laying groundwork",
	"Setting up",
	"Bootstrapping",
	"Initializing",
	"Loading",
	"Preparing",
	"Warming up",
	"Spinning up",
	"Powering up",
	"Activating",
	"Engaging",
	"Mobilizing",
	"Deploying",
	"Executing",
	"Running",
	"Operating",
	"Performing",
	"Delivering",
	"Shipping",
	"Wrapping up",
}

// randomVerb returns a random spinner verb.
func randomVerb() string {
	return spinnerVerbs[rand.Intn(len(spinnerVerbs))]
}
