/// 194 spinner verbs — ported verbatim from spinnerverbs.go
#[allow(dead_code)]
pub const VERBS: [&str; 194] = [
    "thinking",
    "processing",
    "computing",
    "analyzing",
    "calculating",
    "evaluating",
    "examining",
    "exploring",
    "generating",
    "identifying",
    "investigating",
    "learning",
    "measuring",
    "observing",
    "parsing",
    "querying",
    "reading",
    "reasoning",
    "searching",
    "simulating",
    "synthesizing",
    "testing",
    "transforming",
    "validating",
    "verifying",
    "writing",
    "compiling",
    "rendering",
    "loading",
    "saving",
    "fetching",
    "downloading",
    "uploading",
    "syncing",
    "connecting",
    "disconnecting",
    "authenticating",
    "authorizing",
    "encrypting",
    "decrypting",
    "compressing",
    "decompressing",
    "encoding",
    "decoding",
    "translating",
    "transcribing",
    "summarizing",
    "categorizing",
    "classifying",
    "clustering",
    "sorting",
    "filtering",
    "mapping",
    "reducing",
    "aggregating",
    "indexing",
    "scanning",
    "crawling",
    "archiving",
    "restoring",
    "backing up",
    "migrating",
    "deploying",
    "provisioning",
    "configuring",
    "initializing",
    "bootstrapping",
    "warming up",
    "cooling down",
    "spinning up",
    "spinning down",
    "scaling",
    "optimizing",
    "tuning",
    "balancing",
    "distributing",
    "routing",
    "redirecting",
    "forwarding",
    "broadcasting",
    "multicasting",
    "unicasting",
    "streaming",
    "buffering",
    "caching",
    "invalidating",
    "refreshing",
    "updating",
    "patching",
    "upgrading",
    "downgrading",
    "installing",
    "uninstalling",
    "removing",
    "creating",
    "deleting",
    "modifying",
    "editing",
    "formatting",
    "styling",
    "aligning",
    "positioning",
    "resizing",
    "rotating",
    "flipping",
    "mirroring",
    "cropping",
    "trimming",
    "cutting",
    "copying",
    "pasting",
    "duplicating",
    "cloning",
    "forking",
    "branching",
    "merging",
    "rebasing",
    "cherry-picking",
    "stashing",
    "pushing",
    "pulling",
    "fetching",
    "committing",
    "reverting",
    "resetting",
    "checking out",
    "switching",
    "comparing",
    "diffing",
    "blaming",
    "annotating",
    "tagging",
    "labeling",
    "marking",
    "flagging",
    "highlighting",
    "bookmarking",
    "favoriting",
    "starring",
    "liking",
    "disliking",
    "voting",
    "ranking",
    "rating",
    "reviewing",
    "approving",
    "rejecting",
    "accepting",
    "denying",
    "granting",
    "revoking",
    "suspending",
    "resuming",
    "pausing",
    "stopping",
    "starting",
    "restarting",
    "reloading",
    "refreshing",
    "clearing",
    "flushing",
    "purging",
    "cleaning",
    "sweeping",
    "vacuuming",
    "defragmenting",
    "rebuilding",
    "reconstructing",
    "reorganizing",
    "restructuring",
    "refactoring",
    "rewriting",
    "reimplementing",
    "redesigning",
    "rearchitecting",
    "remodeling",
    "renovating",
    "restoring",
    "recovering",
    "repairing",
    "fixing",
    "debugging",
    "troubleshooting",
    "diagnosing",
    "profiling",
    "benchmarking",
    "monitoring",
    "watching",
    "tracking",
    "logging",
    "auditing",
    "recording",
    "capturing",
    "snapping",
];

/// Braille spinner frames
pub const FRAMES: [&str; 4] = ["⠋", "⠙", "⠹", "⠸"];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spinner_verbs_count() {
        assert_eq!(VERBS.len(), 194);
    }

    #[test]
    fn spinner_frames_count() {
        assert_eq!(FRAMES.len(), 4);
    }

    #[test]
    fn spinner_rotation_wraps() {
        let mut verb_idx = 0;
        let mut frame = 0;
        for _ in 0..500 {
            frame = (frame + 1) % 4;
            if frame == 0 {
                verb_idx = (verb_idx + 1) % 194;
            }
        }
        assert_eq!(verb_idx, 500 / 4 % 194);
        assert_eq!(frame, 500 % 4);
    }
}
